name       : haskell-th-expand-syns
version    : 0.4.2.0
release    : 1
source     :
    - http://hackage.haskell.org/package/th-expand-syns-0.4.2.0/th-expand-syns-0.4.2.0.tar.gz : 66fed79828e9a13375f0f801f5ecc3763186667228ad91e19919219ff1654db9
license    : BSD-3-Clause
component  : programming.haskell
summary    : Expands type synonyms in Template Haskell ASTs 
description: |
    Expands type synonyms in Template Haskell ASTs 
builddeps  :
    - haskell-cabal-install
    - haskell-syb
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
