name       : haskell-th-expand-syns
version    : 0.4.5.0
release    : 3
source     :
    - https://hackage.haskell.org/package/th-expand-syns-0.4.5.0/th-expand-syns-0.4.5.0.tar.gz : 5e909e674bc6311d4a8c2376df1e5bda2d8ecde8d79ec8d3d51f59c5bc779cdc
license    : BSD-3-Clause
component  : programming.haskell
summary    : Expands type synonyms in Template Haskell ASTs
description: |
    Expands type synonyms in Template Haskell ASTs
builddeps  :
    - haskell-cabal-install
    - haskell-syb-devel
rundeps    :
    - devel:
        - haskell-syb-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
