name       : haskell-th-expand-syns
version    : 0.4.4.0
release    : 2
source     :
    - https://hackage.haskell.org/package/th-expand-syns-0.4.4.0/th-expand-syns-0.4.4.0.tar.gz : cc0f52d1364ace9ba56f51afd9106a5fe01ed3f5ae45c958c1b0f83be0a6f906
license    : BSD-3-Clause
component  : programming.haskell
summary    : Expands type synonyms in Template Haskell ASTs
description: |
    Expands type synonyms in Template Haskell ASTs
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-syb
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
